### ISSUE TITLE
UnhandledPromiseRejectionWarning (Download aborted)

### ISSUE THREAD

**Issue by Alsweider** [Salies/steam-screenshot-backup-tool#5]
Hello, thanks for all the work remaking the tool. I have tested the new version with my Steam account again. Side note: Additionally to npm I had to enter npm i piexifjs to make it work. 

My results: The tool found 6100 of my 6143 pictures (123 pages). In the new version the number stays consistant, meaning, when I start the app.js a second time, it detects 6100 again and not a different number (which was a problem in the old Python version). 
However, the download cancels every time after 942 pictures. In this version it is not possible for me to surpass this number of downloads by restarting the app anymore. In the Python version, the bug appeared randomly at different positions of the list, so I could restart the tool over and over again until I had the bulk of my pictures saved.
Also I don't know where the downloaded pictures in the Javascript version are located. It doesn't seem to create folders for the screenshots in the app directory. 

Here is the error from the console: 

```
Downloading DATA FOR screenshot 940 of 6100.
Data written.
Downloading DATA FOR screenshot 941 of 6100.
Data written.
Downloading DATA FOR screenshot 942 of 6100.
(node:22608) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'textContent' of null
    at __puppeteer_evaluation_script__:1:30
    at ExecutionContext._evaluateInternal (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async getScreenshotUrl (C:\Users\User\steam-screenshot-backup-tool\modules\getScreenshotUrl.js:30:22)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\Page.js:860:43)
    at Page.<anonymous> (C:\Users\User\steam-screenshot-backup-tool\node_modules\puppeteer\lib\helper.js:112:23)
    at getScreenshotUrl (C:\Users\User\steam-screenshot-backup-tool\modules\getScreenshotUrl.js:30:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:22608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Salies** [comment]
> Also I don't know where the downloaded pictures in the Javascript version are located. It doesn't seem to create folders for the screenshots in the app directory.

At this point the program was not downloading the screenshots yet, just gathering data for it.

A specific glitch is happening in this 942th screenshot, so I'll take a look at it. Apparently it is something related to the game name, that or the page isn't loading at all.

**Comment by Salies** [comment]
Yep, got it. In my code, I just assumed every screenshot featured a game name, but this one doesn't!

https://steamcommunity.com/sharedfiles/filedetails/?id=711145122

Didn't even know it was possible to add a "nameless" game into Steam hahaha. Onto fixing that.

**Comment by Salies** [comment]
@Alsweider Tested and it's working now. Also fixed the piexifjs thing. Just do a `git pull` in the repo folder and you'll be good to go, I believe.

I'll be closing this. If any other error surfaces, feel free to open another issue. Thank you for helping me debug my app!
